[workspace]
members = [".", "ellidri-unicase"]


[package]
name = "ellidri"
version = "1.0.0-alpha"
authors = ["Hubert Hirtz <hubert.hirtz@laposte.net>"]
edition = "2018"
description = "A kawai IRC server"
homepage = "https://github.com/hhirtz/ellidri"
repository = "https://github.com/hhirtz/ellidri"
readme = "README.md"
keywords = ["irc"]
categories = ["network-programming"]
license = "ISC"


[dependencies]
# Runtime
futures = { version = "0.3", default-features = false }
native-tls = { version = "0.2", default-features = false }
tokio = { version = "0.2", default-features = false, features = ["rt-core", "io-util", "tcp", "sync"] }
tokio-tls = { version = "0.3", default-features = false }

# Case-insensitive HashMap.
# Separated from the main crate because it contains unsafe code.
ellidri-unicase = { version = "1.0.0", path = "ellidri-unicase" }

# Logging
env_logger = { version = "0.7", default-features = false }
log = { version = "0.4", default-features = false, features = ["max_level_trace", "release_max_level_info"] }

# Time
chrono = { version = "0.4", default-features = false, features = ["clock"] }

# Capabilities
lazy_static = { version = "1", default-features = false }
