[package]
name = "ellidri"
version = "1.0.0-alpha"
authors = ["Hubert Hirtz <hubert.hirtz@laposte.net>"]
edition = "2018"

[dependencies]
# Runtime
futures = "0.1"
native-tls = "0.2"
tokio = "0.1"
tokio-tls = "0.2"

# Logging
env_logger = { version = "0.7", default-features = false }
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }

# Time
chrono = "0.4"

# Capabilities
lazy_static = "1"
