[package]
name = "ellidri"
version = "0.5.0"
authors = ["Taiite <hubert.hirtz@laposte.net>"]
edition = "2018"

[dependencies]
# Runtime
futures = "0.1"
native-tls = "0.2"
tokio = "0.1"
tokio-tls = "0.2"

# Logging
env_logger = { version = "0.6", default-features = false }
log = "0.4"

# Config
serde = { version = "1", features = ["derive"] }
toml = "0.5"

# Time
chrono = "0.4"
