# Example configuration file.
# All commented values are optional.
# Follow the TOML format: https://github.com/toml-lang/toml#toml

# REQUIRED VALUES

# The IRC server domain.
# Type: String
# It must be a valid domain name.
domain = "ellidri.localdomain"

# OPTIONAL VALUES

# The IPs and TCP ports to which to bind.
# Type: Array of { addr: String, [tls_cert: String, tls_key: String] }
#bind_to_address = [ { addr = "0.0.0.0:6667" } ]

# Modes that are set automatically when channels are created.
# Type: String
# It must be a valid <modes> parameter of the MODE command. For the complete
# list of modes, see the following link:
# https://tools.ietf.org/html/rfc2811.html#section-4
# The '+' is optional.
#default_chan_mode = "+nt"

# The log filter.
# Type: String
# Valid values are:
# - "trace": report incoming and outgoing messages.
# - "debug": report clients actions (default for dev builds).
# - "info": report new/closed connections (default for releases).
# - "warn": report warnings.
# - "error": report critical errors/bugs in the program.
log_level = "trace"

# The message of the day.
# Type: String
# If not set, the server will send an error to new clients and when they issue
# an "MOTD" command.
#motd = """
#It can span on multiple lines.
#
#Empty lines are not ignored.
#"""

# The number of threads used by ellidri.
# Type: Number
# It must be between 1 and 32768.
#worker_threads = 1
